### ISSUE TITLE
Publish 4.1.0?

### ISSUE THREAD

**Issue by tm1000** [Weble/ZohoClient#14]
Can we publish 4.1.0? Might need to update books to reference 4.1.0 (It requires 4.0)

Also CRM still needs to have v5 merged into master and then it can also use 4.1.0

**Comment by Skullbock** [comment]
Hi @tm1000 i've published 4.1.0 of this library, 5.1.0 of zoho books and 5.0.0 of zoho crm.
Feel free to PR any changes that can be required or any addition to the docs

Thanks  again!
