### ISSUE TITLE
Online mode... getGrantCodeConsentUrl doesn't exist

### ISSUE THREAD

**Issue by adriacobo** [Weble/ZohoClient#18]
Hi!!

Thanks for this Client!!

I'm trying to do a middleware to share some project information with my client... but in the example, you share the function getGrantCodeConsentUrl doesn't exist.

Thanks again!!

**Comment by Skullbock** [comment]
Hi! Yes, that's an old method, that we removed because it just did 

```$_GET['code']```

You can use your preferred library to get the `code` param from the url itself.

Can you PR the doc change by any chance?
Thanks!

**Comment by adriacobo** [comment]
Thanks @tm1000 !!
